# Site settings
title: "Hello Bytes"
logo: logo.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: aaron.s.china@outlook.com
description: > # this means to ignore newlines until "url:"
  Hello Bytes is a technology blog.
url: "https://hellobytes.cn" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: hello-bytes
github_username:  hello-bytes

permalink: pretty
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
